run:
  timeout: 5m
  tests: false

linters:
  disable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gosec
    - revive
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    severity: warning
  gosec:
    excludes:
      - G104

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

